services:
    _defaults:
        autowire: true
        autoconfigure: true

    vs_users.form.type.registration:
        class: App\Form\RegistrationForm
        tags:
            - { name: form.type, alias: vs_users_registration }
        arguments:
            - '%vs_users.model.users.class%'
            - '@vs_application.repository.locale'
            - "@request_stack"
            - '%vs_application.model.application.class%'
            - '%vs_users.model.user_roles.class%'
            - '@security.helper'
            - '%vs_users.registration_form_required_fields%'
    
    vs_users.form.type.profile:
        class: App\Form\ProfileFormType
        tags:
            - { name: form.type, alias: vs_users_profile }
        arguments:
            - '%vs_users.model.users.class%'
            - '@vs_application.repository.locale'
            - '@request_stack'
            - '%vs_application.model.application.class%'
            - '%vs_users.model.user_roles.class%'
            - '@security.helper'
            - '%vs_users.profile_form_required_fields%'
